dist: trusty
sudo: false

language: node_js
node_js:
  - '10.15.3'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

install:
  - npm rebuild node-sass
  - npm install --ignore-scripts

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox