#############################################################
##                    ENVIRONMENT VARIABLES                ##
##                                                         ##
## RELEASE_TRAVIS ------> 1 to activate automatic releases ##
## USER_TRAVIS ---------> GitHub user                      ##
## EMAIL_TRAVIS --------> GitHub email                     ##
## BRANCH_TRAVIS -------> branch for releases (master)     ##
## TOKEN_TRAVIS --------> GitHub personal token            ##
## ZIP_TRAVIS ----------> release zip name (soundgo.zip)   ##
## VERSION_TRAVIS ------> release version                  ##
## SUBVERSION_TRAVIS ---> release subversion               ##
## SPRINT_TRAVIS -------> sprint id                        ##
#############################################################

dist: trusty
sudo: false

language: node_js
node_js:
  - '10.15.3'

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules

install:
  - npm update
  - npm install --ignore-scripts
  - nodejs node_modules/node-sass/scripts/install.js
  - npm rebuild node-sass

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - if [[ $TRAVIS_BRANCH == $BRANCH_TRAVIS ]] && [[ $RELEASE_TRAVIS == "1" ]]; then git archive --format zip --output ./$ZIP_TRAVIS.zip $BRANCH_TRAVIS; echo "Source code generated properly."; fi

before_deploy:
  - git config --local user.name $USER_TRAVIS
  - git config --local user.email $EMAIL_TRAVIS
  - export GIT_TAG=SoundGo-v.$VERSION_TRAVIS.$SUBVERSION_TRAVIS.$SPRINT_TRAVIS.$TRAVIS_BUILD_NUMBER
  - git tag -a $GIT_TAG -m "Generated tag from Travis CI build $TRAVIS_BUILD_NUMBER"

deploy:
  provider: releases
  api-key:
    secure: $TOKEN_TRAVIS
  file: "./$ZIP_TRAVIS.zip"
  skip_cleanup: true
  on:
    branch: $BRANCH_TRAVIS
    condition: $RELEASE_TRAVIS = 1
    tags: false

notifications:
  email: false
